apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: acm-general-config-policy
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-operators
    server: https://kubernetes.default.svc
  project: default
  source:
#    directory:
#      jsonnet: {}
#      recurse: false
    path: gitops/acm-general-config-policy
    repoURL: https://github.com/crscottau/openshift-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true