apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: acs-central
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-operators
    server: https://kubernetes.default.svc
  project: default
  source:
#    directory:
#      jsonnet: {}
#      recurse: false
    path: gitops/acs-central
    repoURL: https://github.com/crscottau/openshift-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}

