apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-http-server
  namespace: test  
  labels:
    app: go-http-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-http-server
  template:
    metadata:
      labels:
        app: go-http-server
    spec:
      containers:
      - name: go-http-server
        image: harbor.spenscot.ddns.net/library/go-http-server:1.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
          requests:
            memory: "32Mi"
            cpu: "50m"

