apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"  
  name: custom-ca
  namespace: openshift-config
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDKTCCAhGgAwIBAgIUHubMsJOdUBa9VLGXjDaHtyxiPBswDQYJKoZIhvcNAQEL
    BQAwJDEiMCAGA1UEAwwZcTZiYnQuZHluYW1pYy5vcGVudGxjLmNvbTAeFw0yNDA1
    MDcwNDA3MThaFw0yNTA0MjgwNDA3MThaMCQxIjAgBgNVBAMMGXE2YmJ0LmR5bmFt
    aWMub3BlbnRsYy5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCt
    di+pTs8LCLTr+HAPSxOWVF0GV+j+zDaBXBJpAxAYBnF2tqCgIL9xO5GZskXNIJOw
    bNtrze3l251uHtCvw6N9nTEPLlmUAd+DwRCobI7xaAsq9MKHPUnqKUNwIM6XyMmt
    ivRZXxeDWO5T6mpqB33LjU24bKCps5BqZgruwOSEzfNujCSV7uycBXqd4kx8npuf
    Dg/atYfUEhUAeqDFb9VavgPlAKP3XSmBjhXp4w43Hz2bGiG8VjESlYek5qDWEwKI
    jnEGw5uHL0QB3UH/QHjmguQgnlaUDp3JLM153QPtBQ1BgBhjEqYpQOZ7pYawhBAQ
    IWqT1nZqbHoVv+JTdSJLAgMBAAGjUzBRMB0GA1UdDgQWBBQII5eyc5juOx6I8tVB
    iAiMWmfLRjAfBgNVHSMEGDAWgBQII5eyc5juOx6I8tVBiAiMWmfLRjAPBgNVHRMB
    Af8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQBwGO+ZNYEBD5VOGYCRhu+y3xIH
    cHbGSSESFI6OBK7rNTHwNJaVMpsTkqG+6q5qYerKbR+5U3bDiNV3+W86J+jnyq4Z
    ziWEBI7GFG67rAaxLqImMVFl7h/TIg2esRM67rqxsoNoSxVIIUmGcAZaOPBSsrYI
    kph1Z/o4uJBjtEbEWNQp9UeyD3SahqNjfTYl8VsIfd4nriv9cmzaMbxis1ELZl6g
    ue+JGdFHrlLU3qjZTrgNQNEPelcgjtWfoTgqZhemhzW3NbF9VO9sFDs9tuwMcDB8
    2NpuSxVfVZqIHhXcg/k4AIjKPJdi4gzO2ycs1YMGk/SRMbgj1UsmoLcqHFx5
    -----END CERTIFICATE-----
